### ISSUE TITLE
Mac下 CHM格式显示乱码

### ISSUE THREAD

**Issue by wakerman** [doyoe/css-handbook#10]
图就不截了，应该是字符集的编码的问题。
我用read CHM 打开的

**Comment by mqliutie** [comment]
侧边栏和正文的编码为啥不一样，，，

**Comment by moxiea** [comment]
看来还是windows适合看chm，你们试试把chm解压转成html文件吧

**Comment by ydq** [comment]
我用的是Enolsoft CHM View，我电脑上有一大堆chm，其中唯独有两个easyUI的chm默认就是OK的，其他都要手动指定UTF-8，其中一个chm，手动强制指定UTF-8和GBK 都不会乱码很奇怪，另外一个，强制UTF-8乱码，强制GBK恢复正常。

**Comment by gucong3000** [comment]
各位，mac乱码问题已经完美解决，请在此下载最新chm
https://ci.appveyor.com/api/projects/gucong3000/css-book/artifacts/css.zip

@doyoe 
@huixisheng 
@moxiea 
@mqliutie 
@wakerman 
@xxxcat 
@ydq 
@zenoven

**Comment by ydq** [comment]
@gucong3000 修改的版本测试有效，期待合并到官方版本~~~👍👍👍👍👍

**Comment by gucong3000** [comment]
依赖appveyor的ci系统构建而成，本地运行的话，会破坏代码库中文件的字符集。

**Comment by doyoe** [comment]
@gucong3000 麻烦把解决mac乱码这块提交一个 PR 吧，我merge一下

**Comment by doyoe** [comment]
@all 

v4.2.4 今天发布了，Mac乱码的问题解决了，感谢 @gucong3000 一直以来的支持。
