### ISSUE TITLE
关于margin为百分比的情况

### ISSUE THREAD

**Issue by jackPanyj** [doyoe/css-handbook#100]
手册上是这样的：
`<percentage>：用百分比来定义外补白。水平（默认）书写模式下，参照其包含块 width 进行计算，其它情况参照 height ，可以为负值`

其中 `其它情况参照 height`  这句话不是很理解。

自己查的文献资料上是这样写的：

`<percentage>: A <percentage> always relative to the width of the containing block.`

[参考链接](http://devdocs.io/css/margin-top)

**Comment by doyoe** [comment]
这里说的其实是指书写模式的不同

默认书写模式是水平的，假设将书写模式改为了纵向，情况就会变化

**Comment by jackPanyj** [comment]
好的～原来是这个啊～明天我测试下～
