### ISSUE TITLE
最新的2个发布版 在windows 10 64bit 显示是空白的，完全没有内容怎么办？

### ISSUE THREAD

**Issue by tobefox** [doyoe/css-handbook#103]
首先能做这个的真是牛！不过我有个问题：
最新的2个发布版 在windows 10 64bit 显示是空白的（能够显示目录），完全没有内容怎么办？如题，有办法？现在win10很多呀

**Comment by doyoe** [comment]
在 chm 图标上邮件点击属性，然后点解除锁定

**Comment by gucong3000** [comment]
楼上正解
