### ISSUE TITLE
横线（-）与 波浪线（~）的区别是什么？

### ISSUE THREAD

**Issue by JobbyM** [doyoe/css-handbook#104]
## 问题定位：

在CSS（Contain CSS3）> 取之于单位 Values and Units > 颜色（Color） 下的HSLA 中的取值中

## 问题片段：

```
H：
S：
L：Lightness（亮度）。取值为：0.0% - 100.0%
A：Alpha透明度。取值为0~1之间
```

## 问题描述：

其中**0.0% - 100.0%** 与 **0.0% ~ 100.0%** 的区别是什么？
其中**0 - 1** 与 **0 ~ 1** 的区别是什么？

为什么在文中会有上述不同写法呢？

**Comment by doyoe** [comment]
好细心，其实这2种写法并没有什么区别，就是书写的时候不严谨导致的，我修订一下，都改成 "-" 的方式表达

**Comment by JobbyM** [comment]
ok!
