### ISSUE TITLE
E[att|="val"]{ sRules } not work in chrome54, **如果属性值仅为val，也将被选择**

### ISSUE THREAD

**Issue by scopewu** [doyoe/css-handbook#115]
>选择具有att属性且属性值为以val开头并用连接符"-"分隔的字符串的E元素，**如果属性值仅为val，也将被选择**。

```css
[class|="manage-money"]{
  //
}
```
在开发过程中，chrome54上面的样式并没有作用于`class="manage-money"`的元素。

**Comment by doyoe** [comment]
你应该这么写：

```css
[class|="manage"]{
    /* do something */
}
```

这样的话，所有以 "manage-" 开头的类名都将被命中（同时还包括 manage）

**Comment by doyoe** [comment]
已添加了更详尽的描述，下个版本可见 :)
