### ISSUE TITLE
构建工具升级建议

### ISSUE THREAD

**Issue by gucong3000** [doyoe/css-handbook#118]
@doyoe 在我的fork中，构建工具已经升级多次啦，目前有四大功能：
- html 语法检查
- `兼容性`表格自动根据[caniuse](http://caniuse.com/)数据自动生成
- chm 自动编译
- 持续集成服务(https://ci.appveyor.com/project/gucong3000/css-book)

如果你喜欢其中的功能，可以告诉我，我会发PR过来。
https://github.com/gucong3000/css-book

**Comment by doyoe** [comment]
@gucong3000 兼容性表格这项暂时先不加（这个对目前来看变动有点大），其它几个都不错，感谢来 PR :)

**Comment by gucong3000** [comment]
兼容性表格功能未启用

**Comment by gucong3000** [comment]
另外，这两年此手册的更新速度显著下降，发版频率明显滞后，建议不要将大量时间花在以下行为：
- 删掉旧的，较老的文档数据。这些数据可以作为资料查询，删除他们不会提高文档质量，反而给我带来了一些困扰。
- 人工维护本来可以由IDE来批量操作的HTML
- 人工编写编写兼容性数据，而非采纳更可靠、更全面的第三方数据来源
