### ISSUE TITLE
水平垂直居中的对象

### ISSUE THREAD

**Issue by maixing** [doyoe/css-handbook#127]
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta charset="utf-8" />
<title>position_CSS参考手册_web前端开发参考手册</title>
<meta name="author" content="Joy Du(飘零雾雨), dooyoe@gmail.com, www.doyoe.com" />
<style>
#position {
	position: absolute;
	top:50%;
	left: 50%;
	width: 150px;
	height: 40px;
	margin: -20px 0 0 -85px;
	padding: 0 10px;
	background: #eee;
	line-height: 2.4;
}
</style>
</head>
<body>
<div id="position">水平垂直居中的对象</div>
</body>
</html>

**Comment by doyoe** [comment]
不好意思，没看懂你想表达的意思是什么

**Comment by doyoe** [comment]
方便的话，请重新描述一遍，或新开一个 issue
