### ISSUE TITLE
<h1>column-rule-width:dotted</h1>应为<h1>column-rule-style:dotted</h1>

### ISSUE THREAD

**Issue by hf-li** [doyoe/css-handbook#128]
<h1>column-rule-width:dotted</h1>应为<h1>column-rule-style:dotted</h1>

**Comment by doyoe** [comment]
fixed by commited [dcb07aa](https://github.com/doyoe/css-handbook/commit/dcb07aabe9df7ab6932ce2bf3d6ba852fe250330)
