### ISSUE TITLE
align-items：flex-end解释错了

### ISSUE THREAD

**Issue by kujian** [doyoe/css-handbook#131]
http://css.doyoe.com/properties/flex/align-items.htm
align-items：flex-end 

应该是理解成：

弹性盒子元素的侧轴（纵轴）结束位置的边界紧靠住该行的侧轴结束边界。

而不是起始位置

**Comment by doyoe** [comment]
fixed by commited [f388988](https://github.com/doyoe/css-handbook/commit/f388988f6fca3db8267b57100e1b6336e4f2b7cd)
