### ISSUE TITLE
CSS参考手册 捐赠的弹窗 web版二次打开 有时候不出现

### ISSUE THREAD

**Issue by Jungley8** [doyoe/css-handbook#134]
CSS参考手册 捐赠的弹窗 web版二次打开 有时候不出现

浏览器：chrome
重新方法：
1.点击 捐赠
2.点击 About 飘零雾雨
3.点击 捐赠

**Comment by doyoe** [comment]
fixed by commited [121fd07](https://github.com/doyoe/css-handbook/commit/121fd074cb440648915f4757a62a0877cf44e704)
