### ISSUE TITLE
box-sizing兼容性视图有误

### ISSUE THREAD

**Issue by gucong3000** [doyoe/css-handbook#36]
没有-ms-box-sizing的用法。
另外我增补了padding-box的内容
http://ridge/css-book/properties/user-interface/box-sizing.htm

**Comment by doyoe** [comment]
这个已更正，你说得是对的，没有 -ms- 。
至于 padding-box value 暂时不考虑增加，因为这种use case太少，w3c specs可能会移除该值，同时，基本上没有厂商实现了它
