### ISSUE TITLE
cursor属性: *.jpg 重复

### ISSUE THREAD

**Issue by wangwen1220** [doyoe/css-handbook#38]
原文：
Firefox, Chrome, Safari既支持特定图片类型也支持常见的*.jpg, *.gif, *.jpg等图片格式。 

应为：
Firefox, Chrome, Safari既支持特定图片类型也支持常见的*.png, *.gif, *.jpg等图片格式。 

相关版本V4.1.5

**Comment by doyoe** [comment]
将在 v4.1.6 中修订，谢谢反馈
