### ISSUE TITLE
关于属性选择符的说明

### ISSUE THREAD

**Issue by readyou** [doyoe/css-handbook#40]
关于E[att|="val"]的说明好像有点小问题：
原描述：选择具有att属性且属性值为以val开头并用连接符"-"分隔的字符串的E元素。
实际上应该是：属性值为val(-\w+)*，连接符"-"不是必须的。

**Comment by doyoe** [comment]
应该分开来说，假设有如下例子：

```
li[class|="a"]{color:#f00;}

<div class="a">1</a>
<div class="ab">2</a>
<div class="a-b">3</a>
```

将会命中 1，3 这两个节点，2被跳过，如果以白话一点的描述，应该说成是：选择具有att属性且属性值为以val开头并用连接符"-"分隔的字符串的E元素，如果属性值仅为val，也将被选择。

**Comment by doyoe** [comment]
将在 v4.1.6 中修订，谢谢反馈
