### ISSUE TITLE
用户界面 box-sizing 值的问题

### ISSUE THREAD

**Issue by citywallebs** [doyoe/css-handbook#43]
w3cschool上的值有 inherit(规定应从父元素继承 box-sizing 属性的值),参考手册说没有继承性，求解惑。

**Comment by doyoe** [comment]
这个意思是说box-sizing有inherit这个value，当设置了这个值的时候，将会继承父元素的box-sizing设置

**Comment by gucong3000** [comment]
inherit
initial
这两个都属于隐式的，所有css属性均可使用的取值
建议在“CSS3参考手册 » 取值与单位列表 ”章节增加两个页面来介绍这两种特殊取值

**Comment by doyoe** [comment]
@gucong3000 其实v4.1.7 WD已经加了，你们可能没注意看
