### ISSUE TITLE
关于左边栏水平滚动条的问题

### ISSUE THREAD

**Issue by Master-Inspire** [doyoe/css-handbook#44]
![2015-02-08-2032-003](https://cloud.githubusercontent.com/assets/9047578/6096558/805aa832-afd2-11e4-8aca-4e09e6336127.png)

左边栏是固定宽度为270，在*skin\layout.css*中。
*skin\layout.css*
`#side{width:300px;}`
`#main{left:310px;}`
让main和side增加30，水平滚动条就消失了。

**Comment by doyoe** [comment]
主要是因为不想让左侧占据太多的阅读空间，所以限制了宽度。现在改成将部分导航的标题缩短的方式来解决这个问题
