### ISSUE TITLE
\values\functional\calc().htm

### ISSUE THREAD

**Issue by gucong3000** [doyoe/css-handbook#46]
<ol class="support-info">
				<li>IE9下，使用在background-position会使浏览器崩溃。</li>
			</ol>

**Comment by gucong3000** [comment]
IE9下，在background-position属性中，取值为calc()会使浏览器崩溃

**Comment by doyoe** [comment]
这个case是实测或者有其它资料来源？

**Comment by doyoe** [comment]
已补充
