### ISSUE TITLE
\values\image\radial-gradient().htm

### ISSUE THREAD

**Issue by gucong3000** [doyoe/css-handbook#47]
`<li id="support2">IE6.0-9.0使用私有滤镜来实现该效果: <a href="http://msdn.microsoft.com/en-us/library/ms532997(VS.85,loband).aspx" rel="external" class="external" target="_blank">progid:DXImageTransform.Microsoft.Gradient()</a></li>`
请删除此行，IE并不能使用滤镜来兼容此属性

**Comment by gucong3000** [comment]
其他描述渐变方面的页面，除外linear-gradient().htm，均有此问题其他描述渐变方面的页面，除外linear-gradient().htm，均有此问题

**Comment by doyoe** [comment]
已修复
