### ISSUE TITLE
\properties\positioning\position.htm

### ISSUE THREAD

**Issue by gucong3000** [doyoe/css-handbook#48]
文件第二行写错啦
`<html lang="zh-cmn-Hansn">`
应该是：
`<html lang="zh-cmn-Hans">`
建议用编辑器批量替换所有页面的此行，不要手写
手写可能出现上述错误

**Comment by gucong3000** [comment]
文件第二行写错啦
<html lang="zh-cmn-Hansn">
应该是：
<html lang="zh-cmn-Hans">
建议用编辑器批量替换所有页面的此行，不要手写
手写可能出现上述错误

**Comment by doyoe** [comment]
OK，已修
