### ISSUE TITLE
目录和页面编码不一致

### ISSUE THREAD

**Issue by berniejiang** [doyoe/css-handbook#57]
在mac 中 切到 utf-8 时，页面显示正确目录乱码，切到GB2312/GBK时 目录正确，页面乱码。

**Comment by jakeslee** [comment]
同样的问题。怎么切换都不行。。。

**Comment by gucong3000** [comment]
此问题无解，看在线版本吧http://css.doyoe.com/

**Comment by jakeslee** [comment]
@gucong3000 我觉得可以页面和目录都使用GBK编码。可以参考jQuery中文手册的方式。

**Comment by gucong3000** [comment]
@jakeslee 如果这个issue的讨论者或者点赞特别多，我就改造现有的构建工具，按你说的办，在打包chm前，转换文件编码为GBK。

**Comment by gucong3000** [comment]
最近我在我的fork中，对构建工具做了重构，现在有实现GBK编码的可能了。但是我不用mac，而且我觉得即便提交PR，@doyoe 十有八九也不会去合并。再况且，貌似工作量不小呢。

**Comment by gucong3000** [comment]
@berniejiang \ @jakeslee

时隔一年，此问题终于得到解决，以后请从这个地方下载最新手册，Mac下不乱码
https://ci.appveyor.com/api/projects/gucong3000/css-book/artifacts/bin/css.zip

**Comment by doyoe** [comment]
问题与 Issues [#10](https://github.com/doyoe/css-handbook/issues/10) 相同
