### ISSUE TITLE
columns页面的疑惑

### ISSUE THREAD

**Issue by lroronoazoro** [doyoe/css-handbook#59]
http://css.doyoe.com/properties/multi-column/columns.htm 此页面的兼容性中出现橙色是何解....还有类似页面
Multi-column 此下面的属性页面全都出现橙色, 橙色有什么特殊意义吗?

**Comment by doyoe** [comment]
橙色是以往版本表示需要加厂商前缀的标识，后续会逐渐修改成新的标识方式
