### ISSUE TITLE
属性-内补白-说明中第五条是否准确？

### ISSUE THREAD

**Issue by whwiGrado** [doyoe/css-handbook#60]
原文：
非替代(non-Replaced)行内元素可以使用该属性设置左、右两边的内补丁；若要设置上、下两边的内补丁，必须先使该对象表现为块级或内联块级。

标准里没说啊，是否误认为是margin的vertical方向无效
http://www.w3.org/TR/CSS21/box.html#padding-properties

**Comment by doyoe** [comment]
> Although margins, borders, and padding of non-replaced elements do not enter into the line box calculation, they are still rendered around inline boxes.

尽管不可替换元素的margin，border和padding不会算入行盒的计算，它们仍然渲染在内联盒周围。

**Comment by doyoe** [comment]
这意味着此时内外补白及边框都不会对关联元素产生影响，因为它们只是被绘出来，但不会计入生成盒的尺寸
