### ISSUE TITLE
background-position css3 [3、4 values] 说明有误

### ISSUE THREAD

**Issue by whwiGrado** [doyoe/css-handbook#63]
Properties -> background -> background-position
说明中的第二条：
给偏移量添加关键字时只有边界left-right-top-bottom，而不能是center。

[标准中说的是](http://www.w3.org/TR/css3-background/#the-background-position)
If three or four values are given, then each <percentage> or<length> represents an offset and must be preceded by a keyword, which specifies from which **edge** the offset is given. 

edge应该不包括center。

**Comment by doyoe** [comment]
感谢提醒，已经4.2.2中修复，请关注新版本，谢谢
