### ISSUE TITLE
修改示例代码，点击运行还是执行回最初的代码

### ISSUE THREAD

**Issue by Belssing** [doyoe/css-handbook#64]
http://www.css88.com/book/css/properties/font/font-weight.htm
我是在此修改了示例代码，已经删除了部分内容想尝试不同效果，但点击运行之后还是本来的代码的样子；也就是说，运行没有用

**Comment by gucong3000** [comment]
@doyoe 我来开个分支修改此问题咋样？

**Comment by doyoe** [comment]
OK啊

**Comment by gucong3000** [comment]
https://github.com/doyoe/css-handbook/pull/68
已修复，请审查代码。

**Comment by doyoe** [comment]
OK, TKS, 已合并分支

**Comment by Belssing** [comment]
@gucong3000  已修复我之前提过的问题？我今天再试了下还是不行。再描述一下，就是说修改示例框里面的语句，再点击运行，但是还是会执行回原来最初的示例代码，不是我已经修改过了的。
