### ISSUE TITLE
flex-direction的取值错误

### ISSUE THREAD

**Issue by MarkSky** [doyoe/css-handbook#67]
页面上：

取值：
row：
    横向从左到右排列（左对齐），默认的排列方式。
row-reverse：
    反转横向排列（右对齐，从后往前排，最后一项排在最前面。
column：
    纵向排列。
row-reverse：
    反转纵向排列，从后往前排，最后一项排在最上面。

正确：

取值：

row：
    横向从左到右排列（左对齐），默认的排列方式。
row-reverse：
    反转横向排列（右对齐，从后往前排，最后一项排在最前面。
column：
    纵向排列。
column-reverse：
    反转纵向排列，从后往前排，最后一项排在最上面。

**Comment by doyoe** [comment]
已修正，下个版本可见 :)
