### ISSUE TITLE
Pixels说明文字错误

### ISSUE THREAD

**Issue by jhrxx** [doyoe/css-handbook#71]
http://css.doyoe.com/values/length/px.htm 与 http://css.doyoe.com/values/length/length.htm 页面对于Pixels长度单位的定义相互矛盾： 在length页面px是显示在绝对长度单位内， px页面显示“相对长度单位。像素（Pixels）。 ”

**Comment by jhrxx** [comment]
MDN上有详细的说明：https://developer.mozilla.org/en-US/docs/Web/CSS/length#Absolute_length_units

px
Relative to the viewing device.
For screen display, typically one device pixel (dot) of the display.
For printers and very high resolution screens one CSS pixel implies multiple device pixels, so that the number of pixel per inch stays around 96.

px实际上是绝对长度单位 
但是显示的长度是相对显示屏幕的分辨率而改变的

**Comment by doyoe** [comment]
感谢提出勘误，已在4.2.2中修复，请关注新版本
