### ISSUE TITLE
关于 writing-mode 属性的支持度

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [doyoe/css-handbook#72]
现在 Firefox 已经开始实现了 `writing-mode` 属性的支持，在 38 版本打开 about:config，把 layout.css.vertical-text.enabled 改成 true 就能生效。建议把这个加到参考手册里面。

**Comment by doyoe** [comment]
所有的需要用户修改设置才能生效的默认都当成是不支持，因为实际情况下，无法要求用户去做这个操作

**Comment by gucong3000** [comment]
以前文档中有“实验性质”这种特殊图例，在火狐中这种属于典型的“实验性质”的css属性，但@doyoe貌似已经放弃对“实验性质”这种属性的支持啦

**Comment by KrasnayaPloshchad** [comment]
Firefox 41.0 已经默认开启这个模式的支持，参考手册可以更新了。
https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

**Comment by gucong3000** [comment]
@doyoe 考虑一下呗

**Comment by KrasnayaPloshchad** [comment]
Firefox 43.0 还开始支持像 IE 那样的属性值，就是 tb-lr、lr-tb 这样的值，MDN 网站上说这还是 SVG 标准里面的一部分。

**Comment by doyoe** [comment]
@KrasnayaPloshchad 已更新Firefox41.0+对`writing-mode`属性的支持，不过对于`tb-rl`,`lr-tb`等值Firefox并不计划在CSS中支持，而是只针对SVG1。详情请看：https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode#Values

**Comment by KrasnayaPloshchad** [comment]
👏
