### ISSUE TITLE
@keyframes说明中一处错别字

### ISSUE THREAD

**Issue by seallow** [doyoe/css-handbook#73]
页面地址：http://css.doyoe.com/rules/@keyframes.htm
原文：• 当然，也可以不适用关键字from和to，而都使用<percentage>
应为：• 当然，也可以不使用关键字from和to，而都使用<percentage>

适用 -> 使用

**Comment by gucong3000** [comment]
描述的真详细啊，太好了，我这边的fork先改了哦。
http://gucong3000.github.io/css-book/rules/@keyframes.htm

**Comment by doyoe** [comment]
已修改，谢谢反馈 :)
