### ISSUE TITLE
html语法错误，6个文件

### ISSUE THREAD

**Issue by gucong3000** [doyoe/css-handbook#76]
<p>1 error found in D:\www\css-book\properties\flex\order.htm<br>
	[L93:C5] Tag must be paired, Missing: [ &lt;/div&gt; ] (tag-pair)<br>
	&lt;/li&gt;</p>
<p>3 errors found in D:\www\css-book\properties\media-queries\monochrome.htm<br>
	[L78:C1] Special characters must be escaped : [ &lt; ]. (spec-char-escape)<br>
	&lt;?xml-stylesheet media=&quot;not screen and (monochrome)&quot; rel=&quot;stylesheet&quot; href=&quot;example.css&quot; ?&gt;&lt;/xmp&gt;&lt;/code&gt;&lt;/blockquote&gt;<br>
	[L78:C91] Special characters must be escaped : [ &gt; ]. (spec-char-escape)<br>
	&lt;?xml-stylesheet media=&quot;not screen and (monochrome)&quot; rel=&quot;stylesheet&quot; href=&quot;example.css&quot; ?&gt;&lt;/xmp&gt;&lt;/code&gt;&lt;/blockquote&gt;<br>
	[L80:C5] Tag must be paired, No start tag: [ &lt;/li&gt; ] (tag-pair)<br>
	&lt;/li&gt;</p>
<p>2 errors found in D:\www\css-book\properties\media-queries\width.htm<br>
	[L79:C1] Special characters must be escaped : [ &lt; ]. (spec-char-escape)<br>
	&lt;?xml-stylesheet media=&quot;not screen and (width:800px)&quot; rel=&quot;stylesheet&quot; href=&quot;example.css&quot; ?&gt;&lt;/xmp&gt;&lt;/code&gt;&lt;/blockquote&gt;<br>
	[L79:C92] Special characters must be escaped : [ &gt; ]. (spec-char-escape)<br>
	&lt;?xml-stylesheet media=&quot;not screen and (width:800px)&quot; rel=&quot;stylesheet&quot; href=&quot;example.css&quot; ?&gt;&lt;/xmp&gt;&lt;/code&gt;&lt;/blockquote&gt;</p>
<p>2 errors found in D:\www\css-book\rules\@media.htm<br>
	[L81:C1] Special characters must be escaped : [ &lt; ]. (spec-char-escape)<br>
	&lt;?xml-stylesheet media=&quot;screen and (width:800px)&quot; rel=&quot;stylesheet&quot; href=&quot;example.css&quot; ?&gt;&lt;/xmp&gt;&lt;/code&gt;&lt;/blockquote&gt;<br>
	[L81:C88] Special characters must be escaped : [ &gt; ]. (spec-char-escape)<br>
	&lt;?xml-stylesheet media=&quot;screen and (width:800px)&quot; rel=&quot;stylesheet&quot; href=&quot;example.css&quot; ?&gt;&lt;/xmp&gt;&lt;/code&gt;&lt;/blockquote&gt;</p>
<p>1 error found in D:\www\css-book\selectors\relationship\e-child-f.htm<br>
	[L64:C56] Special characters must be escaped : [ &gt; ]. (spec-char-escape)<br>
	&lt;blockquote class=&quot;gquote-cont&quot;&gt;&lt;code&gt;&lt;xmp&gt;.demo &gt; div {</p>
<p>3 errors found in D:\www\css-book\values\image\image-set().htm<br>
	[L102:C7] Special characters must be escaped : [ &lt; ]. (spec-char-escape)<br>
	&lt;td class=&quot;support&quot;rowspan=&quot;2&quot;&gt;15.0-28.0&lt;br /&gt;&lt;sup class=&quot;fix&quot;&gt;-webkit-&lt;/sup&gt; &lt;sup&gt;&lt;a href=&quot;#support1&quot;&gt;#1&lt;/a&gt;&lt;/sup&gt;&lt;/td&gt;<br>
	[L102:C37] Special characters must be escaped : [ &gt; ]. (spec-char-escape)<br>
	&lt;td class=&quot;support&quot;rowspan=&quot;2&quot;&gt;15.0-28.0&lt;br /&gt;&lt;sup class=&quot;fix&quot;&gt;-webkit-&lt;/sup&gt; &lt;sup&gt;&lt;a href=&quot;#support1&quot;&gt;#1&lt;/a&gt;&lt;/sup&gt;&lt;/td&gt;<br>
	[L102:C122] Tag must be paired, No start tag: [ &lt;/td&gt; ] (tag-pair)<br>
	&lt;td class=&quot;support&quot;rowspan=&quot;2&quot;&gt;15.0-28.0&lt;br /&gt;&lt;sup class=&quot;fix&quot;&gt;-webkit-&lt;/sup&gt; &lt;sup&gt;&lt;a href=&quot;#support1&quot;&gt;#1&lt;/a&gt;&lt;/sup&gt;&lt;/td&gt;<br>
</p>

**Comment by doyoe** [comment]
已修复 :)

**Comment by doyoe** [comment]
在4.2.2版本中发布
