### ISSUE TITLE
border-radius percentage 在老版本的chrome 和 safari下不支持

### ISSUE THREAD

**Issue by gehuangyi20** [doyoe/css-handbook#77]
border-radius 的值可以是length也可以是percentage，但是percentage在老版本的chrome和safari下不支持。

具体可以参考https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

**Comment by doyoe** [comment]
嗯，这个问题确实存在，不过那已经是非常古老的浏览器版本上才有的问题，估计得追溯到2010年或更早前了，所以其实可以不用太在意，不过我还是会在4.2.2的版本中加上一个备注，谢谢
