### ISSUE TITLE
多处DEMO中，css3语法错误

### ISSUE THREAD

**Issue by gucong3000** [doyoe/css-handbook#79]
```CSS
    background:linear-gradient(top,#fff,#000);
```

应更正为：

```CSS
    background: linear-gradient(to bottom, #fff, #000);
```

linear-gradient在w3c提为正式标准后，语法发生了变化，按旧语法写，浏览器不认，此行css不生效

有此问题的页面（包括但不限于）：
\properties\animation\animation-duration.htm
\properties\animation\animation-direction.htm

**Comment by doyoe** [comment]
已修复，将在4.2.2版本中发布
