### ISSUE TITLE
关于margin的适用元素

### ISSUE THREAD

**Issue by liumulin614** [doyoe/css-handbook#84]
标准里的原文是：all elements except elements with table display types other
than table-caption, table and inline-table，意思应该是所有元素除了表格类元素中不具有table-caption, table 和 inline-table属性的元素吧？做了下实验margin也确实可以用于display为table,inline-table和table-caption的

**Comment by doyoe** [comment]
嗯，没错，手册里也是这么写的啊：

“所有元素，除非 table | inline-table | table-caption 的表格类元素之外”

**Comment by liumulin614** [comment]
奥。。对的，又仔细读了一下，断字应该是除...非XXX之外，我读成了除非...XXX之外了，谢谢
