### ISSUE TITLE
gradient线性变换建议放在与动画、过渡同一树目录下，方便查找

### ISSUE THREAD

**Issue by 52fhy** [doyoe/css-handbook#91]
同属CSS3的新属性，建议将`gradient`线性变换与`动画`、`过渡`等属性放在同一树目录下，方便查找。感觉`gradient`属性参考手册里不是很多，希望能补充更多。参考：http://www.runoob.com/css3/css3-gradients.html

**Comment by doyoe** [comment]
http://css.doyoe.com/values/image/gradient.htm

**Comment by 52fhy** [comment]
手册里是有介绍，只是藏得太深了，所以建议将gradient线性变换与动画、过渡等属性放在同一树目录下，方便查找。谢谢。

**Comment by doyoe** [comment]
@52fhy gradient和transform，transition, animation这些特性之间并没有直接关联，CSS手册其实是按分类来做了目录，gradient属于“值”类别。

如果是为了能够快速的查找到gradient，可以在手册的[速查表](http://css.doyoe.com/css3-quicksearch.htm)里使用 ctrl+f 来查找。

**Comment by 52fhy** [comment]
谢谢

在 2016-04-06 10:24:56，"Joy Du" <notifications@github.com> 写道：


@52fhy gradient和transform，transition, animation这些特性之间并没有直接关联，CSS手册其实是按分类来做了目录，gradient属于“值”类别。

如果是为了能够快速的查找到gradient，可以在手册的速查表里使用 ctrl+f 来查找。
