### ISSUE TITLE
-webkit-overflow-scrolling虽然不标准，但是移动web开发却非常实用的一个属性

### ISSUE THREAD

**Issue by ydq** [doyoe/css-handbook#96]
-webkit-overflow-scrolling:touch;
在ios设备上，除了body以外的其他独立滚动的元素在滚动时非常生硬（没有平滑滚动，没有惯性滚动，没有滚动回弹），设置这个属性后可以使有滚动条的元素（如div）获得非常好的平滑滚动以及滚动回弹的效果。

**Comment by doyoe** [comment]
OK，这个后面加一下 :)

**Comment by doyoe** [comment]
-webkit-overflow-scrolling 属性已添加，下个版本可见 :)
